[package]
name = "currencies"
version = "0.1.0"
authors = ["João Oliveira <hello@jxs.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.8.0"
hyper = "0.13.0-alpha.2"
warp =  { git = "https://github.com/jxs/warp.git" }
hyper-rustls = "0.18.0-alpha.1"
serde-xml-rs = "0.3.1"
tokio = "0.2.0-alpha.5"
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
futures-preview = "0.3.0-alpha.18"
